### ISSUE TITLE
Fix certificate issues

### ISSUE THREAD

**Issue by kevinearls** [os-observability/tempo-operator#40]
After adding the webhooks for #39 I got the following after deploying the operator:

```
E0921 13:57:47.355694       1 leaderelection.go:330] error retrieving resource lock tempo-operator-system/8b886b0f.grafana.com: Get "[https://10.96.0.1:443/apis/coordination.k8s.io/v1/namespaces/tempo-operator-system/leases/8b886b0f.grafana.com](https://10.96.0.1/apis/coordination.k8s.io/v1/namespaces/tempo-operator-system/leases/8b886b0f.grafana.com)": context canceled
1.6637686673557637e+09	ERROR	setup	problem running manager	{"error": "open /tmp/k8s-webhook-server/serving-certs/tls.crt: no such file or directory"}
main.main
	/workspace/main.go:100
runtime.main
	/usr/local/go/src/runtime/proc.go:250
```

**Comment by frzifus** [comment]
Since `cert-manager.io/inject-ca-from` is set, i assume its not there because cert-manager didnt put it there.

tomorrow morning I can check it.

See: 
- [config/default/webhookcainjection_patch.yaml](https://github.com/os-observability/tempo-operator/blob/150245ba8d4b7ffbde02e5fd1df2eb21a60cb986/config/default/webhookcainjection_patch.yaml#L8)
- [CA Injector](https://cert-manager.io/docs/concepts/ca-injector/)

**Comment by pavolloffay** [comment]
I have started looking into this as it is blocking me

**Comment by frzifus** [comment]
seems the webhook injection patches havent been enabled.

```
$  k get pods -n tempo-operator-system 
NAME                                                READY   STATUS    RESTARTS   AGE
tempo-operator-controller-manager-c7f98ccff-m7d78   2/2     Running   0          2m2s
```
